"""Regenerate docs/walkthrough.md: one statement's life, through the real tools.

Every step runs a real cp-* command against a fresh database and prints the
tables it changed — new rows marked, changed cells shown as old → new. Run it
after changing the tools; if a step no longer behaves as the story says, it
stops with the command's output.

    .venv/bin/python examples/walkthrough.py
"""

import os
import shlex
import sqlite3
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "walkthrough.md"
DB = str(Path(tempfile.mkdtemp()) / "project.db")
ENV = dict(os.environ, CP_DB=DB, PATH=f"{ROOT / '.venv' / 'bin'}:{os.environ['PATH']}")

TABLES = {
    "statements": ("SELECT id, kind, status, deliverable_id AS D, text FROM statements", 1),
    "links": ("SELECT from_id, relation, to_id FROM links", 3),
    "statement_reasons": ("SELECT statement_id, concern_id FROM statement_reasons", 2),
    "approvals": ("SELECT statement_id, agent_id AS agent FROM approvals", 2),
    "concerns": ("SELECT id, statement_id AS S, kind, raised_by, addressed_to, status, "
                 "closed_round AS closed, acted_on, body FROM concerns", 1),
    "answers": ("SELECT id, concern_id AS C, answered_by, kind, verdict, reply, body FROM answers", 1),
    "deliverables": ("SELECT id, name, status FROM deliverables", 1),
    "agents": ("SELECT role, active, joined_round FROM agents WHERE active = 1", 1),
    "turns": ("SELECT id, round, seq, agent_id AS agent, status, summary FROM turns", 1),
    "project_state": ("SELECT round, phase, status, paused_reason, paused_ref FROM project_state", 0),
}
AGENT_COLS = {"raised_by", "addressed_to", "answered_by", "agent"}
lines = []


def snapshot():
    if not os.path.exists(DB):
        return {name: {} for name in TABLES}
    conn = sqlite3.connect(DB)
    conn.row_factory = sqlite3.Row
    roles = {r["id"]: r["role"] for r in conn.execute("SELECT id, role FROM agents")}
    snap = {}
    for name, (query, key) in TABLES.items():
        rows = [dict(r) for r in conn.execute(query)]
        for r in rows:
            for col in AGENT_COLS & r.keys():
                r[col] = roles.get(r[col], r[col])
        snap[name] = {(tuple(r.values())[:key] if key else i): r for i, r in enumerate(rows)}
    return snap


def cell(value):
    if value is None:
        return "·"
    return str(value).replace("\n", " ").replace("|", "/")


def step(title, *commands, expect_refusal=None):
    """Run commands (all in one step), then print what changed."""
    before = snapshot()
    lines.append(f"### {title}\n")
    for command in commands:
        # A command may carry text its output must contain: ("cp-turn next", "T-4 pm").
        command, must = command if isinstance(command, tuple) else (command, None)
        run = subprocess.run(command, shell=True, env=ENV, capture_output=True, text=True, cwd=ROOT)
        output = (run.stdout + run.stderr).strip()
        refused = run.returncode != 0
        if (refused != bool(expect_refusal) or (expect_refusal and expect_refusal not in output)
                or (must and must not in output)):
            sys.exit(f"step '{title}' did not go as the story says:\n$ {command}\n{output}")
        lines.append(f"```\n$ {command}\n{output}\n```\n")
    after = snapshot()
    unchanged = []
    for name in TABLES:
        changed = [k for k in after[name] if after[name][k] != before[name].get(k)]
        if not changed:
            unchanged.append(name)
            continue
        cols = list(after[name][changed[0]].keys())
        lines.append(f"**{name}**\n")
        lines.append("| | " + " | ".join(cols) + " |")
        lines.append("|---|" + "---|" * len(cols))
        for k in changed:
            old, new = before[name].get(k), after[name][k]
            cells = [cell(new[c]) if old is None or old[c] == new[c]
                     else f"{cell(old[c])} → **{cell(new[c])}**" for c in cols]
            lines.append(f"| {'🆕' if old is None else ''} | " + " | ".join(cells) + " |")
        lines.append("")
    if unchanged:
        lines.append(f"*Unchanged: {', '.join(unchanged)}.*\n")


def turn(role, summary, *commands):
    """One agent's whole turn: open it, act, close it with a summary."""
    step(f"{role}'s turn", ("cp-turn next", f" {role} (round"), *commands,
         f"cp-turn end --agent {role} --summary {shlex.quote(summary)}")


def human(summary, *commands):
    step("the human's turn", "cp-turn start --agent human", *commands,
         f"cp-turn end --agent human --summary {shlex.quote(summary)}")


lines += ["# Walkthrough: one statement's life",
          "",
          "*Generated by `examples/walkthrough.py` against the real tools. Every table a step "
          "changed is shown; 🆕 marks a new row, `old → new` a changed cell.*", ""]

lines.append("## Round 1 — the brief and the interview\n")
step("the human gives the brief",
     "cp-init --brief 'An employee hub where staff request leave and managers approve it.'")
turn("pm", "Asked the human who approves leave and what happens on silence.",
     "cp-concern --from pm --to human --kind question --on S-1 "
     "--body 'Who approves a request, and what happens if they never respond?'")
step("the loop is paused for the human", "cp-turn next", expect_refusal="paused on C-1")
human("Answered who approves leave.",
      "cp-answer --concern C-1 --from human --body 'The employee'\"'\"'s manager. "
      "Nobody should wait more than a week.'")
step("round 1 ends", ("cp-turn next", "round 1 complete"), "cp-round --advance")

lines.append("## Round 2 — Peter turns the brief into statements, and asks for help\n")
turn("pm", "Superseded the brief into a goal, a criterion, v1 scope and the approval rule; "
     "asked for Arty, Quinn and Uma.",
     "cp-review --answer A-1 --by pm --verdict accepted",
     """cp-statement supersede --by pm --old S-1 --because C-1 \
--new '{"kind":"goal","text":"Staff always know where their leave request stands."}' \
--new '{"kind":"scope","deliverable":"D-1","text":"Requesting leave, and approving or declining it."}' \
--new '{"kind":"functional","deliverable":"D-1","text":"A manager approves or declines each leave request."}'""",
     "cp-statement add --by pm --kind success_criterion --measures S-2 --because C-1 "
     "--text 'No request waits more than 5 working days for a decision.'",
     "cp-approve --agent pm --statement S-2", "cp-approve --agent pm --statement S-3",
     "cp-approve --agent pm --statement S-4", "cp-approve --agent pm --statement S-5",
     "cp-staff request --agent architect --by pm --on S-4 --reason 'approvals need a data model'",
     "cp-staff request --agent qa --by pm --on S-4 --reason 'features are concrete'",
     "cp-staff request --agent ux --by pm --on S-4 --reason 'managers act on requests in a UI'")
human("Approved Arty, Quinn and Uma.",
      "cp-staff approve --agent architect --concern C-2",
      "cp-staff approve --agent qa --concern C-3",
      "cp-staff approve --agent ux --concern C-4")

lines.append("## Round 2, continued — the new agents review everything\n")
turn("architect", "Approved the goal, criterion and scope; asked what happens when a manager "
     "never decides.",
     "cp-approve --agent architect --statement S-2", "cp-approve --agent architect --statement S-3",
     "cp-approve --agent architect --statement S-5",
     "cp-concern --from architect --to pm --kind question --on S-4 "
     "--body 'What happens if the manager does nothing for 5 working days?'")
turn("qa", "Approved the goal, criterion and scope; asked whether managers approve from a phone.",
     "cp-approve --agent qa --statement S-2", "cp-approve --agent qa --statement S-3",
     "cp-approve --agent qa --statement S-5",
     "cp-concern --from qa --to ux --kind question --on S-4 "
     "--body 'Can a manager approve from their phone?'")
turn("ux", "Approved everything; handed the phone question to Arty.",
     "cp-approve --agent ux --statement S-2", "cp-approve --agent ux --statement S-3",
     "cp-approve --agent ux --statement S-4", "cp-approve --agent ux --statement S-5",
     "cp-answer --concern C-6 --from ux --reassign-to architect "
     "--body 'Whether the approve screen works on a phone is an architecture call.'")
step("round 2 ends", ("cp-turn next", "round 2 complete"), "cp-round --advance")

lines.append("## Round 3 — answers go back and forth\n")
turn("architect", "Answered the phone question Uma handed me.",
     "cp-answer --concern C-6 --from architect --body 'Yes: the approve screen is responsive.'")
turn("qa", "Accepted Arty's answer on phones.",
     "cp-review --answer A-6 --by qa --verdict accepted")
turn("pm", "Answered Arty on escalation; kept the three staffing requests.",
     "cp-answer --concern C-5 --from pm "
     "--body 'It goes to the manager'\"'\"'s manager after 5 working days.'",
     "cp-statement keep --by pm --because C-2,C-3,C-4")
step("round 3 ends", ("cp-turn next", "round 3 complete"), "cp-round --advance")

lines.append("## Round 4 — Arty accepts; Peter acts on both concerns together\n")
turn("architect", "Accepted the escalation answer; approved S-4 as it stands.",
     "cp-review --answer A-7 --by architect --verdict accepted",
     "cp-approve --agent architect --statement S-4")
turn("qa", "My phone question is settled; approved S-4.",
     "cp-approve --agent qa --statement S-4")
step("Peter's turn opens", ("cp-turn next", " pm (round"), "cp-queue --agent pm")
step("Peter cannot rewrite S-4 while one of its closed concerns is unconsidered",
     """cp-statement supersede --by pm --old S-4 --because C-5 \
--new '{"text":"A manager approves or declines each leave request."}'""",
     expect_refusal="C-6")
step("so Peter keeps C-6 (no change needed) and rewrites S-4 because of C-5",
     "cp-statement keep --by pm --because C-6",
     """cp-statement supersede --by pm --old S-4 --because C-5 \
--new '{"text":"A manager approves or declines each leave request."}' \
--new '{"text":"A request with no decision after 5 working days goes to the manager'"'"'s manager."}'""",
     "cp-approve --agent pm --statement S-6", "cp-approve --agent pm --statement S-7",
     "cp-turn end --agent pm --summary 'Split S-4 into the approval rule and the escalation rule "
     "(C-5); kept C-6.'")
step("round 4 ends", ("cp-turn next", "round 4 complete"), "cp-round --advance")

lines.append("## Round 5 — everyone approves the replacements, and phase 1 converges\n")
for role in ("architect", "qa", "ux"):
    turn(role, "Approved S-6 and S-7.",
         f"cp-approve --agent {role} --statement S-6", f"cp-approve --agent {role} --statement S-7")
step("nothing left for anyone", "cp-turn next", "cp-state")

render = subprocess.run("cp-render requirements", shell=True, env=ENV, capture_output=True,
                        text=True, cwd=ROOT).stdout
lines += ["## The printout: `cp-render requirements`", "", "```markdown", render.rstrip(), "```", ""]

OUT.parent.mkdir(exist_ok=True)
OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT.relative_to(ROOT)}")
